{{- $servicePort := .Values.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: {{ template "fullname" . }}
  labels:
    app: {{ .Values.name }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - backend:
          serviceName: {{ template "fullname" $ }}
          servicePort: {{ $servicePort }}
        path: /
  {{- end }}
  tls:
  - hosts:
    {{- range .Values.ingress.hosts }}
    - {{ . }}
    {{- end }}
    secretName: {{ template "fullname" . }}-certs
