{{- if not .Values.broker.useExistingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.broker.secretName }}
  labels:
    app: {{ .Values.name }}
type: Opaque
data:
  {{ .Values.broker.secretKey}}: {{ .Values.broker.token | b64enc | quote }}
{{- end -}}
