{{- if not .Values.gitlab.useExistingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gitlab.secretName }}
  labels:
    app: {{ .Values.name }}
type: Opaque
data:
  {{ .Values.gitlab.secretKey}}: {{ .Values.gitlab.token | b64enc | quote }}
{{- end -}}
